### ISSUE TITLE
Cannot compile - scoreboard player palette -> ERR LNK2019

### ISSUE THREAD

**Issue by Chameleonhider** [yvt/openspades#383]
Compiling on Win7 64 VS2013 Express I get this error:

`Error LNK2019: unresolved external symbol "int (* palette)[3]" (?palette@@3PAY02HA) referenced in function "private: void __thiscall spades::client::ScoreboardView::DrawPlayers(int,float,float,float,float)" (?DrawPlayers@ScoreboardView@client@spades@@AAEXHMMMM@Z)    C:\Projects\openspades\OpenSpades.msvc\Sources\ScoreboardView.obj   OpenSpades`

Error can be solved by removing "extern" from line ~260 in ScoreboardView.cpp, but then players won't be colored in scoreboard.
(feature introduced in https://github.com/yvt/openspades/pull/340 )

**Comment by VelocityRa** [comment]
This is fixed with my PR above.
